Fix/list comments
The-Bugger-Ducks/owl-partners-back pull request #31
Opened 2023-03-29 12:57 UTC by GabrielCamargoL

## Fix da listagem de comentários

imagem do banco localhost!
![image](https://user-images.githubusercontent.com/55204419/228541638-bb729ba9-3b0e-49c4-8d03-d9ab9cbe59e9.png)

## Fix do status da parceria
![image](https://user-images.githubusercontent.com/55204419/228542132-d1d34ba0-e0ea-4191-bb7f-65f282f9c3dd.png)

``` typescript 
/*
  Warnings:

  - The values [P,PC,PR,ADOCE,ADOCDA,ADOCD,DOCD,PREPES,AESL,AESAG,PA,PF] on the enum `PartnerStatus` will be removed. If these variants are still used in the database, this will fail.
  - You are about to drop the column `commentType` on the `partner_comments` table. All the data in the column will be lost.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "PartnerStatus_new" AS ENUM ('EmProspeccao', 'PrimeiroContatoFeito', 'PrimeiraReuniaoMarcadaRealizada', 'DocumentacaoEnviadaEmAnalise_Parceiro', 'DocumentacaoDevolvida_EmAnaliseAcademy', 'DocumentacaoDevolvida_EmAnaliseLegal', 'DocumentacaoAnalisadaDevolvida_Parceiro', 'EmPreparacaoDeExecutiveSummary_Academy', 'ESEmAnalise_Legal', 'ESEmAnaliseAcademy_Global', 'ProntoParaAssinatura', 'ParceriaFirmada');
ALTER TABLE "partners" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "partners" ALTER COLUMN "status" TYPE "PartnerStatus_new" USING ("status"::text::"PartnerStatus_new");
ALTER TYPE "PartnerStatus" RENAME TO "PartnerStatus_old";
ALTER TYPE "PartnerStatus_new" RENAME TO "PartnerStatus";
DROP TYPE "PartnerStatus_old";
ALTER TABLE "partners" ALTER COLUMN "status" SET DEFAULT 'EmProspeccao';
COMMIT;

-- AlterTable
ALTER TABLE "partner_comments" DROP COLUMN "commentType";

-- AlterTable
ALTER TABLE "partners" ALTER COLUMN "status" SET DEFAULT 'EmProspeccao';

-- DropEnum
DROP TYPE "partnerCommentsType";
```

2023-03-30 21:15 UTC, ThHenrique requested changes
Só mudar a mensagem de validação no DTO de criação de comentário. O restante está ok. Fiquei curioso com o orderby no criação do comentario, enfim, mandou bem lek

🤝🤝🏿

2023-03-31 11:38 UTC, GabrielCamargoL commented on src/modules/partnerComment/partnerComment.service.ts
>  			orderBy: {
não está no insert, está na listagem o git comprimiu as linhas para resumir o arquivo.
![image](https://user-images.githubusercontent.com/55204419/229110394-778e1463-b306-4597-a8a0-edd2bb800f05.png)

2023-03-31 11:39 UTC, GabrielCamargoL commented on src/modules/partnerComment/dto/createComment.dto.ts
>  	@IsNotEmpty({ message: 'O id do usuário(userID) precisa ser fornecido' })
obrigado pelo aviso, realmente passou despercebido com os devidos copia e cola :fire:

2023-03-31 12:53 UTC, ThHenrique approved these changes
Boa meu cumpad

2023-03-31 12:54 UTC, merged